### ISSUE TITLE
How do I initiate a request based on the request parameters of the browser How does cbor decode it? Thank you

### ISSUE THREAD

**Issue by thedownup** [rocklabs-io/ic-py#22]
![image](https://user-images.githubusercontent.com/30197037/148524690-8d4fbf28-84dd-4b97-8c8c-255ee78d11a8.png)

**Comment by ccyanxyz** [comment]
You can use cbor2 package to decode cbor encoded data, hope [this](https://github.com/rocklabs-io/ic-py/blob/main/ic/agent.py#L52) helps.
