### ISSUE TITLE
Import Stoic Identity via seed phrase

### ISSUE THREAD

**Issue by bodily11** [rocklabs-io/ic-py#44]
I know I can export PEM from plug and I can import using Identity.from_pem(private_key). But I was wondering if it was possible to import a Stoic identity via seed phrase. Something like Identity.from_seed(mnemonic). I didn't see anything like this when I looked at methods possible with Identity, so wanted to see if this was going to be supported.

Thanks!

**Comment by ccyanxyz** [comment]
added in https://github.com/rocklabs-io/ic-py/pull/46
