### ISSUE TITLE
validate signature 

### ISSUE THREAD

**Issue by letmejustputthishere** [rocklabs-io/ic-py#64]
it would be nice if we could verify signatures that were created with the dfinity agent

**Comment by Myse1f** [comment]
Did you mean #56 ?

**Comment by letmejustputthishere** [comment]
no i want to validate a  secp256k1 or ed25519 signature made with `@dfinity/identity`

https://erxue-5aaaa-aaaab-qaagq-cai.ic0.app/identity/classes/Ed25519KeyIdentity.html#sign

https://erxue-5aaaa-aaaab-qaagq-cai.ic0.app/identity/classes/Secp256k1KeyIdentity.html#sign

**Comment by Myse1f** [comment]
Added at #65.
You can use `Identity.verify(msg, signature: bytes)` to verify the signature, where `msg` is is bytes or bytes in string format, and signature is bytes.

**Comment by letmejustputthishere** [comment]
awesome, thank you!
