### ISSUE TITLE
provide interface according to candid provided

### ISSUE THREAD

**Issue by letmejustputthishere** [rocklabs-io/ic-py#70]
would be nice if i had access to the method available on a canister and their signatures when i define an actor like this:

```
  ogy = Canister(agent=agent, canister_id=canister_id,
                    candid=ogy_candid)
```

**Comment by Myse1f** [comment]
`Python` is dynamic language, which means it can add property and methods in the runtime. 
But I think the `Pylance` analyze the code based on static analysis. Thus it can't detect the method added in runtime.
