### ISSUE TITLE
why is `0x` added to account ids?

### ISSUE THREAD

**Issue by letmejustputthishere** [rocklabs-io/ic-py#73]
when i stringify an account identifier, `0x` is added. i have to manually remove because appliations on the IC don't work with the `0x` prefix. can it be removed by default and added only when explicitly stated?

**Comment by Myse1f** [comment]
You can use the method `bytes` to get the bytes format. Then use `hex` to get the string without 0x.

**Comment by letmejustputthishere** [comment]
yes, i can also remove the first two chars of the string ^^ but i'm wondering why you add it in the first place?
