### ISSUE TITLE
ValueError: invalid literal for int() with base 10: '_block'

### ISSUE THREAD

**Issue by rapid520** [rocklabs-io/ic-py#87]
return VariantClass(fields)
  File "D:\python\lib\site-packages\ic\candid.py", line 753, in __init__
    self._fields = dict(sorted(field.items(), key=lambda kv: labelHash(kv[0]))) # check
  File "D:\python\lib\site-packages\ic\candid.py", line 753, in <lambda>
    self._fields = dict(sorted(field.items(), key=lambda kv: labelHash(kv[0]))) # check
  File "D:\python\lib\site-packages\ic\utils.py", line 22, in labelHash
    num = int(s[1:])
ValueError: invalid literal for int() with base 10: '_block'

**Comment by Myse1f** [comment]
Pls attach a code snippet that can reproduce the error. It will help much on trouble shooting.

**Comment by rapid520** [comment]
`` with open(r'test.pem','r') as f:
        private_key_1 = f.read()
    plug = Identity.from_pem(private_key_1)
    client = Client(url = "https://ic0.app")
    agent = Agent(plug, client)
    governance_did = open("oru4a-nqaaa-aaaak-acufa-cai.did").read()
    governance = Canister(agent=agent, canister_id='oru4a-nqaaa-aaaak-acufa-cai', candid=governance_did)
    res = governance.trade({
        0:{'quantity':{ 'Sell' : number ,'price' : price}},
        1:{ 'LMT' : Null }, 
        2:[],
        3:[],
        4:[],
        5:[]
    })
    return res

**Comment by rapid520** [comment]
``

> Pls attach a code snippet that can reproduce the error. It will help much on trouble shooting.

` with open(r'test.pem','r') as f:
        private_key_1 = f.read()
    plug = Identity.from_pem(private_key_1)
    client = Client(url = "https://ic0.app")
    agent = Agent(plug, client)
    governance_did = open("oru4a-nqaaa-aaaak-acufa-cai.did").read()
    governance = Canister(agent=agent, canister_id='oru4a-nqaaa-aaaak-acufa-cai', candid=governance_did)
    res = governance.trade({
        0:{'quantity':{ 'Sell' : number ,'price' : price}},
        1:{ 'LMT' : Null }, 
        2:[],
        3:[],
        4:[],
        5:[]
    })
    return res`

**Comment by Myse1f** [comment]
Should be fixed in #89
