### ISSUE TITLE
candid interface file

### ISSUE THREAD

**Issue by 0xYGicp** [rocklabs-io/ic-py#94]
Thanks for good library. I have some questions about candid interface file.
[README.md](https://github.com/rocklabs-io/ic-py#readme)
> 6. Canister
> Create a canister instance with candid interface file and canister id, and call canister method with canister instance:

1. How is creating an instance from a candid file and calling canister different from other common a query_call or update_call that does not use candid files?

2. In the case that a Dapp has no candid file, is there any solution? If ic-py can't do it, can an agent in another language do it?

**Comment by Myse1f** [comment]
> How is creating an instance from a candid file and calling canister different from other common a query_call or update_call that does not use candid files?

By calling through `canister`, you don't need to handle encoding parameters and decoding return values.
`query_raw` and `call_raw` are lower level api. You must provide the struct of parameter and return value.

> In the case that a Dapp has no candid file, is there any solution? 

If you don't provide the candid, it will try to call `__get_candid_interface_tmp_hack` to get the candid result. Otherwise, it will fail to initialize the `canister`.

 > If ic-py can't do it, can an agent in another language do it?

I don't think so. I think candid desciption is a must for Internet Computer Canister. Without it, we don't know what api the canister are exposing.

**Comment by 0xYGicp** [comment]
```
from ic.canister import Canister
from ic.client import Client
from ic.agent import Agent
from ic.candid import encode, decode, Types
from ic.identity import Identity

i1 = Identity()
client = Client(url = "https://ic0.app")
agent = Agent(i1, client)

params = []
params = encode(params)

canister_id = 'cea4l-ryaaa-aaaae-aaa6a-cai'

response = agent.query_raw(canister_id,'__get_candid_interface_tmp_hack',params)
canister_did = response[0]['value']
canister = Canister(agent=agent, canister_id=canister_id, candid=canister_did)
TypeError                                 Traceback (most recent call last)
[<ipython-input-13-c4b54dedaeeb>](https://localhost:8080/#) in <module>
     15 
     16 response = agent.query_raw(canister_id,'__get_candid_interface_tmp_hack',params)
---> 17 canister_did = response[0]['value']
     18 canister = Canister(agent=agent, canister_id=canister_id, candid=canister_did)

TypeError: string indices must be integers
```

**Comment by 0xYGicp** [comment]
I appreciate your response. I tried to use __get_candid_interface_tmp_hack to get the candid result from Rust canister, which doesn't have a candid file, but I received the below error. What is the cause of this error?

```
from ic.canister import Canister
from ic.client import Client
from ic.agent import Agent
from ic.candid import encode, decode, Types
from ic.identity import Identity

i1 = Identity()
client = Client(url = "https://ic0.app")
agent = Agent(i1, client)

params = []
params = encode(params)

canister_id = 'cea4l-ryaaa-aaaae-aaa6a-cai'

response = agent.query_raw(canister_id,'__get_candid_interface_tmp_hack',params)
canister_did = response[0]['value']
canister = Canister(agent=agent, canister_id=canister_id, candid=canister_did)
--------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-13-c4b54dedaeeb>](https://localhost:8080/#) in <module>
     15 
     16 response = agent.query_raw(canister_id,'__get_candid_interface_tmp_hack',params)
---> 17 canister_did = response[0]['value']
     18 canister = Canister(agent=agent, canister_id=canister_id, candid=canister_did)

TypeError: string indices must be integers
```

**Comment by Myse1f** [comment]
Motoko written canister will implement the `__get_candid_interface_tmp_hack` automatically, while Rust one need to implement manually.

For canister that doesn't expose such method, you need to define the `did` manually. Otherwise, use the `query_raw` and `update_raw`.
